language: java
jdk:
  - oraclejdk8
install: /bin/true
script:
  - mvn install -Dskip.unit.tests=true -Dmaven.javadoc.skip=true -V -B
  - jdk_switcher use openjdk6
  - mvn test
notifications:
  email: false