language: java
jdk:
  - oraclejdk8

install: /bin/true

script:
  - mvn install -Dmaven.test.skip=true -Dmaven.javadoc.skip=true -V -B
  - mvn clean test coveralls:report -V -P coverage
  - jdk_switcher use openjdk6
  - mvn test -V